name:                eirini-route-emitter
version:             0.1.0.0
github:              "akshaymankar/eirini-route-emitter"
license:             BSD3
author:              "Akshay Mankar"
maintainer:          "itsakshaymankar@gmail.com"
copyright:           "Akshay Mankar"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/akshaymankar/eirini-route-emitter#readme>

dependencies:
- aeson
- aeson-casing
- attoparsec
- base >= 4.7 && < 5
- base64-bytestring
- bytestring
- containers
- either
- errors
- filepath
- freer-simple
- hoauth2
- http-client
- http-client-tls
- jwt
- kubernetes-client
- kubernetes-client-core
- microlens
- mtl
- oidc-client
- old-locale
- pem
- stm
- text
- time
- timerep
- tls
- typed-process
- unordered-containers
- uri-bytestring
- x509
- yaml
- nats-client

library:
  source-dirs: src

executables:
  eirini-route-emitter:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eirini-route-emitter

tests:
  eirini-route-emitter-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - eirini-route-emitter
    - hspec
    - hspec-attoparsec
